// Generated by CoffeeScript 1.8.0

/**
* @author Josh Bass
*
 */
define(["vendor/backbone"], function(Backbone, Math2) {
  var inventorySectionModel;
  return inventorySectionModel = Backbone.Model.extend({

    /**
    		* initialize a new model, will automatically initialize a new
    		* search
    		* @method initialize
    		*
    		*
     */
    initialize: function(options) {}
  });
});
