// Generated by CoffeeScript 1.8.0

/*
CustomerSectionBarView
@author Josh Bass
 */
define(["vendor/backbone", "plugins/CustomerSection/view/Templates", "css!plugins/CustomerSection/view/res/css/customerUpdatePanel.css"], function(Backbone, Templates, CSS) {
  return Backbone.View.extend({
    className: "customerUpdatePanel pressedborder box_shadow",
    id: "draggable",
    events: {
      "click .closeButton": "closePanel",
      "click .cancelButton": "closePanel",
      "click .updateButton": "updateCustomer"
    },
    initialize: function(model) {
      this.model.on("change:first_name", (function(_this) {
        return function() {
          return _this.$el.find(".firstNameArea").val(_this.model.get("first_name"));
        };
      })(this));
      this.model.on("change:last_name", (function(_this) {
        return function() {
          return _this.$el.find(".lastNameArea").val(_this.model.get("last_name"));
        };
      })(this));
      this.model.on("change:nick_name", (function(_this) {
        return function() {
          return _this.$el.find(".nickNameArea").val(_this.model.get("nick_name"));
        };
      })(this));
      this.model.on("change:email", (function(_this) {
        return function() {
          return _this.$el.find(".emailArea").val(_this.model.get("email"));
        };
      })(this));
      this.model.on("change:address", (function(_this) {
        return function() {
          return _this.$el.find(".addressArea").val(_this.model.get("address"));
        };
      })(this));
      return this.model.on("change:birthday", (function(_this) {
        return function() {
          return _this.$el.find(".birthdayArea").val(_this.model.get("birthday"));
        };
      })(this));
    },

    /*
    		Create the Dialog and return its element
    		@method render
     */
    render: function() {
      this.$el.html(Templates.customerUpdatePanel());
      this.$el.find(".birthdayArea").datepicker();
      return this.$el;
    },
    toggleHidden: function(overlayOn, animate) {
      if (!overlayOn) {
        if (animate) {
          return this.$el.fadeOut("slow");
        } else {
          return this.$el.css("display", "none");
        }
      } else {
        if (animate) {
          return this.$el.fadeIn("slow");
        } else {
          return this.$el.css("display", "");
        }
      }
    },
    closePanel: function() {
      this.toggleHidden(false, true);
      this.model.set("first_name", "");
      this.model.trigger("change:first_name", "");
      this.model.set("last_name", "");
      this.model.trigger("change:last_name", "");
      this.model.set("nick_name", "");
      this.model.trigger("change:nick_name", "");
      this.model.set("email", "");
      this.model.trigger("change:email", "");
      this.model.set("address", "");
      this.model.trigger("change:address", "");
      this.model.set("birthday", "");
      this.model.trigger("change:birthday", "");
      this.model.set("couchid", "");
      this.model.trigger("change:couchid", "");
      this.model.set("couchrev", "");
      return this.model.trigger("change:couchrev", "");
    },

    /*
    		Called after Dialog has been appended, this will set up the prog search
    		list with all known searches
    		@method realized
     */
    realized: function() {
      this.$el.find(".birthdayArea").datepicker();
      this.$el.find(".updateButton").button();
      return this.$el.find(".cancelButton").button();
    },
    updateCustomer: function() {
      var update;
      update = {
        first_name: this.$el.find(".firstNameArea").val(),
        last_name: this.$el.find(".lastNameArea").val(),
        nick_name: this.$el.find(".nickNameArea").val(),
        email: this.$el.find(".emailArea").val(),
        address: this.$el.find(".addressArea").val(),
        birthday: this.$el.find(".birthdayArea").val(),
        _id: this.model.get("couchid"),
        _rev: this.model.get("couchrev")
      };
      console.log("############################### I am inserting");
      $.post("update_user", update);
      this.closePanel();
      return this.model.get("customerViewModel").trigger("change:customerEvent");
    }
  });
});
