// Generated by CoffeeScript 1.8.0

/*
ConfirmDialogView
@author Josh Bass
 */
define(["vendor/backbone", "plugins/ConfirmDialog/view/Templates", 'css!plugins/ConfirmDialog/view/res/css/confirmDialog.css'], function(Backbone, Templates, CSS) {
  return Backbone.View.extend({
    className: "confirmDialog",
    events: {
      "click .dialogYes": "confirm",
      "click .dialogNo": "cancel"
    },
    initialize: function(model) {},

    /*
    		Create the Dialog and return its element
    		@method render
     */
    render: function() {
      this.$el.html(Templates.confirmDialog({}));
      return this.$el;
    },

    /*
    		@method realized
     */
    realized: function() {
      this.$el.css("display", "none");
      this.$el.find(".dialogYes").button();
      return this.$el.find(".dialogNo").button();
    },
    confirmDelete: function(confirmAction) {
      return this.$el.dialog({
        hide: {
          effect: "explode",
          duration: 1000
        },
        title: this.model.get("title"),
        close: (function(_this) {
          return function() {
            console.log("I was closed...");
            if (_this.model.get("actionConfirmed")) {
              console.log("I Was confirmed!! :)");
              confirmAction();
            }
            return _this.model.set("actionConfirmed", false);
          };
        })(this)
      });
    },
    confirm: function() {
      this.model.set("actionConfirmed", true);
      return this.$el.dialog("close");
    },
    cancel: function() {
      return this.$el.dialog("close");
    }
  });
});
